name: Basic

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 16.8
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
  
